# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yubo/src/quagga-0.99.24/cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yubo/src/quagga-0.99.24/cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yubo/src/quagga-0.99.24/cmake/CMakeFiles /home/yubo/src/quagga-0.99.24/cmake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yubo/src/quagga-0.99.24/cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zebra

# Build rule for target.
zebra: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zebra
.PHONY : zebra

# fast build rule for target.
zebra/fast:
	$(MAKE) -f lib/CMakeFiles/zebra.dir/build.make lib/CMakeFiles/zebra.dir/build
.PHONY : zebra/fast

#=============================================================================
# Target rules for targets named zebra-static

# Build rule for target.
zebra-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zebra-static
.PHONY : zebra-static

# fast build rule for target.
zebra-static/fast:
	$(MAKE) -f lib/CMakeFiles/zebra-static.dir/build.make lib/CMakeFiles/zebra-static.dir/build
.PHONY : zebra-static/fast

#=============================================================================
# Target rules for targets named zebra-main

# Build rule for target.
zebra-main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zebra-main
.PHONY : zebra-main

# fast build rule for target.
zebra-main/fast:
	$(MAKE) -f zebra/CMakeFiles/zebra-main.dir/build.make zebra/CMakeFiles/zebra-main.dir/build
.PHONY : zebra-main/fast

#=============================================================================
# Target rules for targets named ospf

# Build rule for target.
ospf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ospf
.PHONY : ospf

# fast build rule for target.
ospf/fast:
	$(MAKE) -f ospfd/CMakeFiles/ospf.dir/build.make ospfd/CMakeFiles/ospf.dir/build
.PHONY : ospf/fast

#=============================================================================
# Target rules for targets named ospf-static

# Build rule for target.
ospf-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ospf-static
.PHONY : ospf-static

# fast build rule for target.
ospf-static/fast:
	$(MAKE) -f ospfd/CMakeFiles/ospf-static.dir/build.make ospfd/CMakeFiles/ospf-static.dir/build
.PHONY : ospf-static/fast

#=============================================================================
# Target rules for targets named ospfd

# Build rule for target.
ospfd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ospfd
.PHONY : ospfd

# fast build rule for target.
ospfd/fast:
	$(MAKE) -f ospfd/CMakeFiles/ospfd.dir/build.make ospfd/CMakeFiles/ospfd.dir/build
.PHONY : ospfd/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... zebra"
	@echo "... zebra-static"
	@echo "... zebra-main"
	@echo "... ospf"
	@echo "... ospf-static"
	@echo "... ospfd"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

